# .gitpod.yml
image:
  file: .gitpod.Dockerfile

tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      ./bin/aws_cli_install.sh

  - name: terraform
    before: |
      ./bin/terraform_cli_install.sh
  
  # random utilities
  - name: utils
    before: |
      sudp apt-get install tree

  - name: powershell
    before: |
      ./bin/powershell_cli_install.sh

